apiVersion: v1
kind: BuildConfig
metadata:
  name: rstudio
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  source:
    type: Git
    git:
      uri: https://github.com/CSCfi/rstudio-openshift.git
      ref: dev
    contextDir: server
  strategy:
    dockerStrategy:
      buildArgs:
        - name: tag
          value: rstudio
  output:
    to:
      namespace: juha-rstudio
      kind: ImageStreamTag
      name: rstudio-test:latest
  triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
          secretReference:
            name: webhooksecret
        type: GitHab
