apiVersion: v1
kind: BuildConfig
metadata:
  name: alpine-python3
  annotations:
    description: Defines how to build the application
    template.alpha.openshift.io/wait-for-ready: "true"
spec:
  source:
    dockerfile: "FROM alpine:latest \n RUN apk --no-cache add python3"
  strategy:
    dockerStrategy:
      buildArgs:
        - name: tag
          value: alpine-python3
  output:
    to:
      kind: ImageStreamTag
      name: alpine-python3:latest
  triggers:
    - type: ImageChange
    - type: ConfigChange